=== giellalt/dict-fkv-nob/script/fkvnob.dtd
<!ELEMENT r (lics, entry+) >
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ELEMENT lic (#PCDATA) >
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA) >
<!ELEMENT sourcenote (#PCDATA) >

<!ELEMENT entry (lemma, stem*, mgr+, refgr?) >
<!ELEMENT lemma (#PCDATA) >
<!ATTLIST lemma pos ( adj | subst | verb | adv | po | pr | num | cc | x ) #IMPLIED
>      
<!--
<!ATTLIST lemma geo ( eva | por | rai | pva)  #IMPLIED >
-->
<!-- tenke hÃ¸gt...
    stemclass ( 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) >
-->


<!ELEMENT stem (#PCDATA)>
<!ELEMENT mgr (restrict?, trgr+)>
<!ELEMENT restrict (#PCDATA)>
<!ELEMENT trgr (trans+, exgr*, syngr*)>
<!ELEMENT trans (#PCDATA)>
<!ATTLIST trans decl (
             -  | d  | f  | fx | f1 | f1x | f3 | 
             m  | mx | mo | m1 | m1b | mix | m2 | m3 | m3x | m4 | 
             n  | nx | no | n1 | n1b | n2 | n2c | n3 | n3b | n3c | n4 | n4b |
             a1 | a2 | a3 | a4 | a5 | ax | adv | p | num |
             v1 | v2 | v3 | v4 | vx | cc | interj | x ) #IMPLIED
    geo  ( eva | por | rai | pva)  #IMPLIED 
 >
<!ELEMENT exgr (ex, extr)>
<!ELEMENT ex (#PCDATA)>
<!ATTLIST ex geo ( eva | por | rai | pva)  #IMPLIED >
<!ELEMENT extr (#PCDATA)>

<!ELEMENT syngr (syn+)>
<!ELEMENT syn (#PCDATA)>

=== giellalt/dict-fkv-nob/src/cc_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../scripts/fkvnob.css"?>
<?xml-stylesheet type="text/xsl" href="../scripts/fkvnob.xsl"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD fkvnob//SE" "../scripts/fkvnob.dtd">
<r>
  <lics>
    <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>

     <ref>Work by Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>

     <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not always
     sorted, or sorted in the wrong order. (If consistent (but wrong) sorting is
     important, use Firefox.)
     </sourcenote>
   </lics>


   <entry>
      <lemma pos="cc">eli</lemma>
      <mgr>
         <trgr>
            <trans decl="cc">eller</trans>
            <syngr>
               <syn>elikk√§</syn>
               <syn>tahi</syn>
            </syngr>
         </trgr>
      </mgr>
   </entry>
   <entry>
      <lemma pos="cc">ette</lemma>
      <mgr>
         <trgr>
            <trans decl="x">at</trans>
         </trgr>
      </mgr>
   </entry>
   <entry>
      <lemma pos="cc">ja</lemma>
      <mgr>
         <trgr>
            <trans decl="x">og</trans>
            <trans decl="x">samt</trans>
         </trgr>
      </mgr>
   </entry>
   <entry>
      <lemma pos="cc">jos</lemma>
      <mgr>
         <trgr>
            <trans decl="x">dersom</trans>
            <trans decl="x">om</trans>
            <trans decl="x">viss</trans>
         </trgr>
      </mgr>
   </entry>
   <entry>
      <lemma pos="cc">mutta</lemma>
      <mgr>
         <trgr>
            <trans decl="x">men</trans>
         </trgr>
      </mgr>
   </entry>
   <entry>
      <lemma pos="cc">tahi</lemma>
      <mgr>
         <trgr>
            <trans decl="cc">eller</trans>
            <syngr>
               <syn>tai</syn>
               <syn>vai</syn>
            </syngr>
         </trgr>
      </mgr>
   </entry>
   <entry>
      <lemma pos="cc">vaikka</lemma>
      <mgr>
         <trgr>
            <trans decl="cc">selv om</trans>
         </trgr>
      </mgr>
   </entry>
</r>
