=== giellalt/dict-fkv-nob/dtd/fkvnob.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( nob | sme | sma | swe | eng | deu | smn | fin | fkv | sms | myv | mhr | sjd | rus | smj ) #IMPLIED
>
<!ATTLIST r
      id ( smenob | nobsme | smnfin | finsmn | finsme | fkvnob | smnsme | smjsme | smesmn | smesmj | smesma | smefin | smasme | smanob | nobsma | smafin | swesma | smeeng |
      nobsmj ) #IMPLIED >

<!--
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( nob | sme | sma | swe | eng | deu | smn | fin | fkv| sms | myv | mhr | sjd | rus | smj ) #IMPLIED
 id ( fkvnob | nobfkv ) #IMPLIED
 >
-->

<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT e ( lg, mg+ ) >
<!-- ATTLIST e reverse NMTOKEN #IMPLIED -->
<!ATTLIST e src CDATA #REQUIRED >
<!ATTLIST e dial (p|r|v|pv|rv|pr|prv) #IMPLIED
 id  CDATA #IMPLIED
 reverse (yes) #IMPLIED
 >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adv | CC | CS | Clt | Interj | 
                  N | Num | Pcle | Po | Pr | Pron | Qu | V ) #IMPLIED >
<!ATTLIST l src NMTOKEN #IMPLIED >
<!ATTLIST l stem ( 2syll | 3syll | weak ) #IMPLIED >
<!ATTLIST l t_type ( Phrase ) #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >
<!ATTLIST l val ( IV | TV ) #IMPLIED >
<!ATTLIST l dial (p|j|v|pv|jv|pj) #IMPLIED >
<!ATTLIST l sem_type ( Obj | Org | Plc ) #IMPLIED >
<!ATTLIST l outer_cases ( True | False ) #IMPLIED >
<!ATTLIST l hid CDATA #IMPLIED >
<!ATTLIST l re CDATA #IMPLIED >
<!ATTLIST l context CDATA #IMPLIED >


<!ELEMENT lg ( l, lemma_ref*, stem*, analysis*, mini_paradigm*, algu?) >
<!ELEMENT lemma_ref (#PCDATA) >
<!ATTLIST lemma_ref lemmaID CDATA #IMPLIED >
<!ELEMENT analysis (#PCDATA|wordform)* >
<!ATTLIST analysis ms CDATA #IMPLIED >
<!ELEMENT wordform (#PCDATA) >
<!ELEMENT mini_paradigm (analysis+) >

<!-- algu = lemma IDs in the algu database -->
<!ELEMENT algu EMPTY >
<!ATTLIST algu
      lekseemi_id CDATA #REQUIRED >
<!ATTLIST algu
      sanue_id CDATA #REQUIRED >

<!ELEMENT mg ( tg+ | xg* ) >


<!ELEMENT stem ( #PCDATA ) >

<!ELEMENT syn ( #PCDATA ) >

<!ELEMENT syng ( syn+ ) >

<!ELEMENT re ( #PCDATA ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t gen ( f | m | n ) #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Adv | CC | CS | Cp | Det | Interj | 
                  N | Num | Po | Pr | Pron | V ) #IMPLIED >
<!ATTLIST t t_type ( expl | Phrase )  #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >

<!ELEMENT tg ( re? | t | syng? | xg? )* >
<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang ( nob ) #REQUIRED >
<!ATTLIST tg dial (p|j|v|pv|jv|pj) #IMPLIED >

<!ELEMENT xg ( x, xt ) >
<!ATTLIST xg re CDATA #IMPLIED >
<!ELEMENT x ( #PCDATA ) >
<!ELEMENT xt ( #PCDATA ) >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-fkv-nob/src/Pr_fkvnob.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="ta;ai">
      <lg>
         <l pos="Pr">ennen</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">før</t>
            <t pos="Pr">tidligere</t>
            <xg>
            <x>Mie en jaksa puhhuut kenenkhään kans ennen aamukaffii.</x>
            <xt>Jeg orker ikke å snakke med noen før morgenkaffen.</xt>
            </xg>
            <xg>
            <x>Ajattele vähäsen ennen ko puhut.</x>
            <xt>Tenk deg litt om før du sier noe.</xt>
            </xg>
            <xg>
            <x>Het olthiin lähtenheet monta viikkoo ennen.</x>
            <xt>De hadde dratt noen uker tidligere.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">heller</t>
            <xg>
               <x>Ennen mie kuolisin, ennen ko antaisin ylön.</x>
               <xt>Jeg vil heller dø enn å gi opp.</xt>
            </xg>
            <xg>
               <x>Hän olis ennen halunu jääđä tänne.</x>
               <xt>Hun hadde heller hatt lyst til å bli igjen.</xt>
            </xg>
         </tg>
      </mg>
   </e>
      <e src="ki">
      <lg>
         <l pos="Pr">päästä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
	       <re>Om tid og sted</re>
            <t pos="Pr">om</t>
            <xg>
            <x>Mie tulen tiiman päästä.</x>
            <xt>Jeg kommer om en time.</xt>
            </xg>  
            <xg>
            <x>Kafea oon neljen kilometrin päästä.</x>
            <xt>Det er fire kilometer til kafeen.</xt>
            </xg>
            </tg>
      </mg>
   </e>   
   <e src="ai">
      <lg>
         <l pos="Pr">eđeltä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">før</t>
            <t pos="Pr">foran</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="Pr">ilman</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">uten</t>
            <xg>
               <x>ilman rahatta</x>
               <xt>uten penger</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pr">jälkhiin</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">etter</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pr">keskele</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">til midt i</t>
            <t pos="Pr">til midt på</t>
            <xg>
               <x>Kirkon rakenethiin keskele kyllää.</x>
               <xt>Kirken ble bygd midt i bygda.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai;es">
      <lg>
         <l pos="Pr">keskelä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">midt i/på</t>
            <xg>
               <x>Mie heräsin keskelä yötä.</x>
               <xt>Jeg våknet midt på natta.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="mk">
      <lg>
         <l pos="Pr">kohti</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">imot</t>
            <t pos="Pr">mot</t>
            <xg>
               <x>Het kävelthiin kohti horisonttii.</x>
               <xt>De gikk rett imot horisonten.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="mk;es">
      <lg>
         <l pos="Pr">kohđi</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">imot</t>
            <xg>
               <x>Het kävelthiin kohđi horisonttii.</x>
               <xt>De gikk rett imot horisonten.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">mot</t>
            <xg>
               <x>Het naakithaan työmiesten pörhään vaaran laittaa alas kohđi kyllää.</x>
               <xt>De sniker seg etter arbeidskarene langs fjellsida ned mot bygda.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pr">likeltä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">fra nærheten av</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pr">liki</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">i nærheten av</t>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="Pr">läpi</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">gjennom</t>
            <t pos="Pr">via</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pr">läpitte</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">gjennom</t>
         </tg>
      </mg>
   </e>
   <e src="ai;es">
      <lg>
         <l pos="Pr">pitkin</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">langs</t>
            <xg>
            <x>Siinä mennee tie pitkin Tenojokivartta.</x>
            <xt>Det går en vei der langs Tanaelvstranden.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="Pr">poikki</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t t_type="Phrase">på den andre sida av</t>
            <xg>
               <x>poikki jokkee</x>
               <xt>på andre sida av elva</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t t_type="Phrase">tvers over</t>
            <xg>
               <x>Souđin poikki vuonon ämmin tykö.</x>
               <xt>Jeg rodde over fjorden til bestemor.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">gjennom</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="Pr">siutte</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
	         <re>om tid</re>
            <t pos="Pr">over</t>
            <xg>
               <x>Kello oon siutte keskiyön.</x>
               <xt>Klokka er over midnatt.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="es;ai">
      <lg>
         <l pos="Pr">sivvu</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
	         <re>om tid</re>
            <t pos="Pr">over</t>
            <t pos="Pr">etter</t>
            <xg>
               <x>Kello oon sivvu keskiyön.</x>
               <xt>Klokka er over midnatt.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="Pr">vaila</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">uten</t>
            <xg>
               <x>Hän oon vastausta vaila.</x>
               <xt>Han står uten svar.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t t_type="Phrase">i underkant av</t>
            <xg>
               <x>Het juosthiin vaila puolen miilan pitukaisen kilvan.</x>
               <xt>De løp en konkurranse som var i underkant av en halv mil lang.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l pos="Pr">vaile</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">uten</t>
            <xg>
               <x>Hän saapi jääđä vastausta vaile.</x>
               <xt>Han får bli stående uten svar.</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t t_type="Phrase">i underkant av</t>
            <t pos="Pr">på</t>
            <xg>
               <x>Kello oon viisi vaile kolme.</x>
               <xt>Klokka er fem på tre.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="Pr">yli</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Pr">over</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-fkv-nob/src/Clt_fkvnob.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/fkvnob.dtd">
<r id="fkvnob" xml:lang="fkv">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e src="ai;es">
      <lg>
         <l pos="Clt">-ki</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">også</t>
            <xg>
            <x>Mieki halluun myötä!</x>
            <xt>Jeg vil også være med!</xt>
            </xg>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="nob">
            <t pos="Adv">enda</t>
            <t pos="Adv">til og med</t>
         </tg>
      </mg>
   </e>
   <e src="ki">
      <lg>
         <l pos="Clt">-khään</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
         <re>ved nekting</re>
            <t pos="Adv">heller</t>
            <xg>
               <x>Mie en halluu sitä. - En miekhään.</x>
               <xt>Jeg vil ikke ha den. - Ikke jeg heller.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ki">
      <lg>
         <l pos="Clt">-khaan</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
         <re>ved nekting</re>
            <t pos="Adv">heller</t>
            <xg>
               <x>Mulla ei ole ruokkaa myötä. - Ei minulakhaan.</x>
               <xt>Jeg har ikke mat meg meg. - Ikke jeg heller.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>
