=== giellalt/dict-fkv-nob/scripts/dict_fkvnob.dtd
<!ELEMENT e ( lg, mg+ ) >
<!ATTLIST e reverse NMTOKEN #IMPLIED >
<!ATTLIST e src CDATA #REQUIRED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l decl NMTOKEN #IMPLIED >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos CDATA #REQUIRED >
<!ATTLIST l src NMTOKEN #IMPLIED >
<!ATTLIST l stem NMTOKEN #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >
<!ATTLIST l val ( IV | TV ) #IMPLIED >

<!ELEMENT lg ( l, stem* ) >

<!ELEMENT mg ( tg ) >

<!ELEMENT r ( e+ ) >

<!ELEMENT stem ( #PCDATA ) >

<!ELEMENT syn ( #PCDATA ) >

<!ELEMENT syng ( syn+ ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t decl ( a1 | a4 | ax | f | m | m1 | x ) #IMPLIED >
<!ATTLIST t gen ( a | a1 | a2 | f | f1 | m | m1 | m2 | n | v | x ) #IMPLIED >
<!ATTLIST t nr NMTOKEN #IMPLIED >
<!ATTLIST t pos CDATA #REQUIRED >
<!ATTLIST t t_type NMTOKEN #IMPLIED >
<!ATTLIST t type NMTOKEN #IMPLIED >

<!ELEMENT tg ( syng | t | xg )* >
<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang ( nob ) #IMPLIED >

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-fkv-nob/src/CS_fkvnob.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet title="Dictionary view" media="screen,tv,projection" href="../../scripts/gt_dictionary.css" type="text/css"?>
<?xml-stylesheet alternate="yes" title="Hierarchical view" media="screen,tv,projection" href="../../scripts/gt_dictionary_alt.css" type="text/css"?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../scripts/dict_fkvnob.dtd">
<r>
   <e src="ta;ai">
      <lg>
         <l pos="CS">ette</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">at</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CS">ettei</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">at ikke</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CS">jos</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">dersom</t>
            <t pos="CS">hvis</t>
            <t pos="CS">om</t>
         </tg>
      </mg>
   </e>
   <e src="ta;ai">
      <lg>
         <l pos="CS">ko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">da</t>
            <t pos="CS">når</t>
            <t pos="CS">enn</t>
            <t pos="CS">som</t>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CS">koska</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">fordi</t>
            <t pos="CS">når</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CS">sillä ko</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">fordi</t>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l pos="CS">että</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">at</t>
         </tg>
      </mg>
   </e>
   <e src="ta">
      <lg>
         <l pos="CS">entä</l>
      </lg>
      <mg>
         <tg xml:lang="nob">
            <t pos="CS">enn</t>
         </tg>
      </mg>
   </e>
</r>
